repos:
    -
      repo: local
      hooks:
        -
          id: sync_notebooks
          name: sync_notebooks
          entry: sync_notebooks.sh
          pass_filenames: false
          language: script
        -
          id: jupytext
          name: jupytext
          entry: jupytext --from ipynb --to py:percent --pre-commit
          pass_filenames: false
          language: python
        -
          id: stage-changes
          name: stage-changes
          entry: git add -u
          pass_filenames: false
          language: system
        -
          id: unstage-ipynb
          name: unstage-ipynb
          entry: git reset HEAD **/*.ipynb
          pass_filenames: false
          language: system